"""removed last name option

Revision ID: 308c18d552de
Revises: 4deb19f76b25
Create Date: 2021-03-02 17:09:18.878378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308c18d552de'
down_revision = '4deb19f76b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
